variables:
    GROUP_NAME: smarttech

stages:
    - Deploy

Deploy:
    stage: Deploy
    only:
        - main
    script:
        - podman-compose up -d --build --force-recreate
    tags:
        - Biopark
    environment:
        name: Production
        url: https://$GROUP_NAME.biopark.smartflow.me
