version: '3'

services:
   shopping-cart:
    build: .
    ports:
      - 8080:8080
            
   mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping-cart
      MYSQL_PASSWORD: 32106
      MYSQL_INITDB_SCRIPT: /docker-entrypoint-initdb.d/mysql_query.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases:/docker-entrypoint-initdb.d
    ports:
        - 3308:3306
      
volumes:
  mysql_data: