version: '3'

services:
   shopping-cart:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
            
   mysql:
    image: docker.io/library/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping-cart
      MYSQL_PASSWORD: 32106
      MYSQL_INITDB_SCRIPT: /docker-entrypoint-initdb.d/mysql_query.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases:/docker-entrypoint-initdb.d
    ports:
        - 2021:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
      
volumes:
  mysql_data:
