version: '3'
services:
  tomcat:
    image: shopping_cart
    ports:
      - "8080:8080"
    networks:
      - my-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 32106
      MYSQL_DATABASE: shoppin-cart
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - my-network

volumes:
  mysql_data: 

networks:
  my-network:
